library/urls.py
from django.urls import path, include
from django.conf.urls.static import static

# from django.conf import settings
from . import views


from . import views

urlpatterns = [
   
    path('', views.index, name='index'),
    path('gamintojai/', views.gamintojai, name='gamintojai'),
    path('gamintojas/<int:gamintojas_id>', views.gamintojas, name='gamintojas'),
    path('products/', views.product_list, name='products'),
    path('products/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('search/', views.search, name='search'),
    path('my_products/', views.LoanedProductsByUserListView.as_view(), name='my-borrowed'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
    path('my_products/<uuid:pk>', views.ProductByUserDetailView.as_view(), name='my-product'),
    path('my_products/new', views.ProductByUserCreateView.as_view(), name='my-borrowed-new'),

] 
urlpatterns += [
    
    path('accounts/', include('django.contrib.auth.urls')),
    
] 

sandelis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView



urlpatterns = [
    path('library/', include('library.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='library/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

library/models.py
from django.db import models
from django.urls import reverse 
import uuid
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from PIL import Image




class Preke(models.Model):
    pavadinimas = models.CharField('Pavadinimas', max_length=200, help_text='Išrinkite prekes tipa(pvz. Batai)')

    def __str__(self):
        return self.pavadinimas
    
    class Meta:
        verbose_name = 'Prekė'
        verbose_name_plural = 'Prekes'

# Create your models here.

class Product(models.Model):
    title = models.CharField('Pavadinimas', max_length=200)
    gamintojas = models.ForeignKey('Gamintojas', on_delete=models.SET_NULL, null=True, related_name='products')
    summary = HTMLField('Aprašymas')
    code =  models.CharField('Prekes kodas', max_length=25, null=True )
    cover = models.ImageField('Nuotrauka', upload_to='covers', null=True)
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Simbolių <a href="https://www.isbn-international.org/content/what-isbn">ISBN kodas</a>')
    preke = models.ManyToManyField(Preke,  help_text='Išrinkite tipa šiai prekei')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])
    
    class Meta:
        verbose_name = 'Produktas'
        verbose_name_plural = 'Produktai'
    
    def display_preke(self):
        return ',' .join(preke.pavadinimas for preke in self.preke.all()[:4])
    
    display_preke.prekeshort_discription = 'Produktas'  #!!!!!?????

    
class ProductInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4, help_text='Unikalus ID')
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True, related_name='instances') 
    size = models.CharField('Dydis',max_length=10)
    due_back = models.DateField('Numatytas gavymas', null=True, blank=True)
    ser_number = models.CharField('Serijos numeris', max_length=25, null=True )
    quantity = models.IntegerField('Kiekis', default=0)
    vartotojas = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    

    LOAN_STATUS = (
        ('a', 'Atvyksta'),
        ('p', 'Parduota'),
        ('r', 'Rezervuota'),
        ('l', 'Likutis'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='l',
        help_text='Statusas',
    )

    @property
    def is_overdue(self):
        if set.due_back and date.today() > self.due_back:
            return True
        return False
    

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_add", "Leisti pridėti prekes"),)
        

    def __str__(self):
        return f'{self.id} ({self.product})'
    
    class Meta:
        verbose_name = 'Produkto lentelė'
        verbose_name_plural = 'Produktų lentelė'
        
def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class Gamintojas(models.Model):
    
    company_name = models.CharField('Gamintojo pavadinimas', max_length=100)
    company_country = models.CharField('Kilmės šalis', max_length=100, null=True)
    description = HTMLField("Aprasymas", max_length=2000, default='')

    class Meta:
        ordering = ['company_name', 'company_country']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.company_name} {self.company_country}' 

    class Meta:
        verbose_name = 'Gamintojas'
        verbose_name_plural = 'Ganintojai'

    def display_products(self):
        return ', '.join(product.title for product in self.products.all()[:4])
    
    display_products.short_discription = 'Produktai'



class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"
    
    class Meta:
        verbose_name = 'Profilis'
        verbose_name_plural = 'profiliai'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (200, 200)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)    

library/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User

# class CustomUserCreationForm(UserCreationForm):
#     email = forms.EmailField(required=True)

#     class Meta:
#         model = User
#         fields = ('username', 'email', 'password1', 'password2')


from .models import Profilis, ProductInstance
from django import forms
from django.contrib.auth.models import User

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']
        

class ProductIntranceForm(forms.ModelForm):
    class Meta:
        model = ProductInstance
        fields = ['product', 'quantity', 'size']

library/views.py
from typing import Any, Dict, Optional
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from .models import Preke, Product, ProductInstance, Gamintojas
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfilisUpdateForm
from django.views.generic import ListView, DetailView, CreateView
from django.db import models

from .models import Product

# Create your views here.
@login_required
# @permission_required('app.can_input_data', raise_exception=True)
# def input_data(request):
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profilis.html', context)




def index(request):
    num_products = Product.objects.all().count()
    num_instances = ProductInstance.objects.all().count()

    num_instances_available = ProductInstance.objects.filter(status__exact='l').count()
    num_gamintojai = Gamintojas.objects.all().count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_products': num_products,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_gamintojai': num_gamintojai,
        'num_visits': num_visits
    }  

    return render(request, 'index.html', context=context)

@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
#             # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else: # jeigu passwordai Nesutampa
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'register.html')

def gamintojai(request):
    paginator = Paginator(Gamintojas.objects.all(), 4)
    page_number = request.GET.get('page')
    paged_gamintojai = paginator.get_page(page_number)
    # gamintojai = Gamintojas.objects.all() nebereikia
    context = {
        'gamintojai': paged_gamintojai
        }
    return render(request, 'gamintojai.html', context=context)

def gamintojas(request, gamintojas_id):
    single_gamintojas = get_object_or_404(Gamintojas, pk=gamintojas_id)
    return render(request, 'gamintojas.html', {'gamintojas': single_gamintojas})


def search(request):
    query = request.GET.get('query')
    search_results = Product.objects.filter(Q(title__icontains=query) | Q(summary__icontains=query) | Q(gamintojas__company_name__icontains=query))
    return render(request, 'search.html', {'products': search_results, 'query': query})


def product_list(request):
    # if request.method == "POST":
    #     pi = ProductInstance( 
            
    #         size = request.POST['size'],
    #         quantity = request.POST['quantity'],
    #         due_back = request.POST['due_back']
    #     )
        
    #     return redirect('index')

    # print(ProductInstance.objects.all())
     
    paginator = Paginator(Product.objects.all(), 6)
    page_number = request.GET.get('page')
    paged_product = paginator.get_page(page_number)
    context = {
        'products': paged_product}
    return render(request, 'product_list.html', context=context)


class LoanedProductsByUserListView(LoginRequiredMixin, generic.ListView):
    model = ProductInstance
    template_name ='user_products.html'
    context_object_name = 'products'
    paginate_by = 10
    
    def get_queryset(self):
        return ProductInstance.objects.filter(vartotojas=self.request.user).filter(status__exact='l').order_by('due_back')


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = "product_detail.html"
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        object = Product.objects.get(pk=self.kwargs['pk'])
        sizes = object.instances.all()
        print(sizes)
        context['instances'] = sizes.order_by('size')
        return context

class ProductByUserDetailView(LoginRequiredMixin, DetailView):
    model = ProductInstance
    template_name = 'user_procuct.html'

class ProductByUserCreateView(LoginRequiredMixin,UserPassesTestMixin, CreateView):
    model = ProductInstance
    fields = ['product', 'status', 'size' ,'quantity' ,'due_back']
    success_url = "/library/my_products/"
    template_name = 'user_product_form.html'
   


    def form_valid(self, form):
        form.instance.vartotojas = self.request.user
        form.instance.status = 'a'
        return super().form_valid(form)
    
    def test_func(self) -> bool | None:
        return not self.request.user.groups.filter(name="sandelio darbuotojai").exists()
    

def product_list(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'product_list.html', context)

library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Sandėlis</title>{% endblock %}
  <meta charset="utf-8">


  {% if request.path == " " %}
    <meta http-equiv="refresh" content="0; url=/library">
  {% endif %}
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
 
  <!-- <link rel="./stylesheet" href="style.css">  -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 

<!-- Add additional CSS in static file -->
  {% load static %}
  <!-- <script src="./script.js" defer></script> -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body >
  <div class="page-container">
    <header>
      <div class="header">
      <!-- <h1><a href="{% url 'index' %}"></a></h1> -->
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">
            <div class="logo">
            <img src="https://rebrand.lt/media/2020/04/Logotipu-kurimas2-Sandelis.jpg" alt="Local file logo"  width="200" height="94"
            class="d-inline-block align-text-top">
            <!-- Sandėlis -->
          </a>
        </div>
          <!-- <a class="navbar-brand" href="#">Navbar</a> -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <!-- <a class="nav-link active" aria-current="{% url 'index' %}">Pradžia</a> -->
              <!-- <a class="nav-link" href="{% url 'index' %}">Pradžia</a>
              <a class="nav-link" href="{% url 'products' %}">Visos prekes</a>
              <a class="nav-link" href="{% url 'gamintojai' %}">Visi gamintojai</a> -->
              
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'profilis' %}">
                    <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                    </svg>
                  {{ user.get_username }}</a></li>
                  <!-- <li class="nav-item"><a class="nav-link" href="{% url 'my-borrowed' %}">mano prekes</a></li> -->
                  
                  <li class="nav-item"><a class="nav-link" href="{% url 'my-borrowed-new' %}?next=/library">Sukurti Nauja Pkeke</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/library">Atsijungti</a></li>
                {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registruotis</a></li>
                {% endif %}
                {% if not user.is_authenticated %}
                {% endif %}
              </ul>
              
              <a>
                <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                <input name="query" class="form-control" type="text" placeholder="Paieška">
                </form>
              </a>
            </div>
          </div>
        </div>
      </nav>
    </div>
    </header>
  
  <br>
  <br>
  <br>
  <div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-1">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Pradžia</a></li>
          <li><a href="{% url 'gamintojai' %}">Visi gamintojai</a></li>
          <li><a href="{% url 'products' %}">Visos prekes</a></li>
          
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-9 ">{% block content %}{% endblock %}</div>
    </div>
    
  </div> 
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</div>



</body>

</html>

library/templates/gamintojai.html
{% extends "base.html" %}

{% block content %}
  <h1>Gamintojai</h1>
  <p>Tiekėjų  sąrašas</p>
  <p>Šiuo metų prekes  mes  gauname  iš:</p>
  {% for a in gamintojai %}
  <li><a href="{% url 'gamintojas' a.id %}">{{a.company_name}} ({{a.company_country}})</a></li>
  {% endfor %}






<div class="container_puslapiai" >
  <nav aria-label="...">
      {% if gamintojai.has_other_pages %}
          <ul class="pagination pagination-md justify-content-center">
              {% for i in gamintojai.paginator.page_range %}
                  {% if gamintojai.number == i %}
                      <li class="page-item active">
                          <a class="page-link">{{ i }}</a>
                      </li>
                  {% else %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                      </li>
                  {% endif %}
              {% endfor %}
          </ul>
      {% endif %}
  </nav>
</div>


<!-- <div class="footer">
    <p>© (MZ) 2023 Mano Svetainė.  Visos teisės saugomos.</p>
</div> -->

{% endblock %}

library/templates/gamintojas.html
{% extends "base.html" %}

{% block content %}
    <div class="container gamintojas">
    <h4>{{ gamintojas.company_name}} ({{ gamintojas.company_country }})</h4>
    <hr/>
    <p>{{ gamintojas.description }}</p>
    </hr>
    </br>
    <h5>Mes turime šias {{ gamintojas.company_name }}  produktai:</h5>
    {% for product in gamintojas.products.all %}
       <li>
        <a href="{% url 'product-detail' product.id %}">{{ product.title }}</a></li> 
    {% endfor %}
    </div>
{% endblock %}

library/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Batų sandėlis</h1>
 
  <p>Šiuo metu turime :</p>

 

  <ul>
    
    <li><strong>Mūsų gamintojai </strong> {{ num_gamintojai }}</li>
    
    <li><strong>Bendras skačius galimų variantų </strong> {{ num_instances }}</li>
    <li><strong>Laisvų galimų variantų</strong> {{ num_instances_available }}</li>
  </ul>
  <!-- <p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p> -->
{% endblock %}

library/templates/product_detail.html
{% extends "base.html" %}

{% block content %}
<div class="product-details">
  <h4>{{ product.title }}</h4>
  <img src="{{ product.cover.url }}" style="margin-bottom: 50px;" class="product-cover">
</div>

<div class="product-info">
  <table>
    <tr>
      <p><strong>Gamintojas:</strong> <a href="{% url 'gamintojas' product.gamintojas.pk %}">{{ product.gamintojas }}</a></p>
    </tr>
    <tr>
      <p><strong>Aprašymas:</strong> {{ product.summary | safe}}</p>
    </tr>
    <tr>
      <p><strong>Prekės kodas:</strong> {{ product.code }}</p>
    </tr>
   

  <div style="margin-left:20px;margin-top:20px">
    <style>
      table, th, td {
        border: 1px solid black;
      }
      </style>
      </head>
      <body>
      
        
   
    <table class="table">
      <thead>
        <tr>
          <th>Statusas</th>
          <th>Atvyksta</th>
          <th>Kiekis</th>
          <th>Dydis</th> 
        
        </tr>
      </thead>
      
      <tbody>
        {% for copy in instances %}
        <tr>
          <td>
            <p class="{% if copy.status == 'l' %}text-success{% elif copy.status == 'p' %}text-danger{% else %}text-warning{% endif %}">
              {{ copy.get_status_display }}
            </p>
          </td>
          {% if copy.status != '' %}
            <td>{{ copy.due_back }}</td>
          {% else %}
            <td></td>
          {% endif %}
          <td>{{ copy.quantity }}</td>
          <td>{{ copy.size }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table> 



 
  

{% endblock %}

library/templates/product_list.html
{% extends "base.html" %}
<link rel="./stylesheet" href="style.css">

{% block content %}

  <h3 style="color:blue;">Produktų sąrašas:</h3>
  <!-- {% if products %}
  <ul>
    {% for product in products %}
      <li>
        <a href="{{ product.id }}">{{ product.title }}</a> ({{product.gamintojas}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Sandėlije tokiu produktų nėra.</p>
  {% endif %} -->

  {% load static %}
  <!-- <h1>Produktų sąrašas</h1></br> -->
  {% if products %}
  <div class="row">
    {% for product in products %}
      <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
          {% if product.cover %}
            <img src="{{ product.cover.url }}" class="card-img-top" alt="...">
          {% else %}
            <img src="{% static 'img/no-image.png' %}" class="card-img-top">
          {% endif %}
          <div class="card-body">
            <p class="card-text"><a href="{{ product.id}}">{{ product.title }}</a></p>
            <h9 class="card-subtitle mb-2 text-muted">{{ product.gamintojas }}</h9>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% else %}
    <p>Sandėlije tokiu produktų nėra.</p>
  {% endif %}

<div class="container_puslapiai">
  <nav aria-label="...">
      {% if products.has_other_pages %}
          <ul class="pagination pagination-md justify-content-center border-radius">
              {% for i in products.paginator.page_range %}
                  {% if products.number == i %}
                      <li class="page-item active">
                          <a class="page-link">{{ i }}</a>
                      </li>
                  {% else %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                      </li>
                  {% endif %}
              {% endfor %}
          </ul>
      {% endif %}
  </nav>
</div>  
     
{% endblock %}

library/templates/profilis.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.nuotrauka.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

library/templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>Registracija</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Vartotojo vardas</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Iki 150 simbolių.</small>
            </div>

            
            
            <div class="form-group">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Nesidalinsime su niekuo, nesiųsime jokio spamo.
                    Reikalingas naujam slaptažodžiui išsiųsti. </small>
            </div>

            <div class="form-group">
                <label for="password">Slaptažodis</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
                    skaičiai</small>
            </div>
            <div class="form-group">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="/login"><strong>Prisijunkite.</strong></a></p>
    </div>

{% endblock %}

library/templates/user_products.html
{% extends "base.html" %}

{% block content %}
    <h3>Mano supildytos prekes </h3>

    {% if productinstance_list %}
    <ul>

      {% for productinst in productinstance_list %} 
      <li class="{% if productinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'product-detail' productinst.product.pk %}">{{producinst.product.title}}</a> ({{ productinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Šiuo metu neivedete nei vienos prekes.</p>
    {% endif %}       
{% endblock %}